name: todo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  google_fonts: ^6.1.0
  responsive_framework: ^1.1.1
  package_info_plus: ^8.0.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  shared_preferences: ^2.2.3
  flutter_staggered_grid_view: ^0.7.0

  #Firebase
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_database: ^10.5.5

  #State management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  #Social Login
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
